# Generated by Django 3.2.23 on 2026-07-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0009_auto_20250811_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BribeIngestionCursor',
            fields=[
                (
                    'account',
                    models.CharField(max_length=56, primary_key=True, serialize=False),
                ),
                ('paging_token', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
